### ISSUE TITLE
crashed after successful run

### ISSUE THREAD

**Issue by victoriavhe** [qiscus/qiscus-chat-sdk-flutter-sample#2]
I tried to run the example  but it crashed after a successful run. 
and it keeps on printing ` Configuring the default Firebase app...` on the console.

**Comment by adicatur** [comment]
Hi @victoriavhe can you share your version of chat SDK flutter and also can have full error

**Comment by victoriavhe** [comment]
I use the same as the example has. actually I just run from this repo.
Here's the log

```
Launching lib/main.dart on iPhone 8 Plus in debug mode...
Running Xcode build...
Xcode build done.                                           62.2s
Configuring the default Firebase app...
Configuring the default Firebase app...
Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available.
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 61964
This was attempt #50. Will retry in 0:00:01.600000.
Configuring the default Firebase app...

```

**Comment by adicatur** [comment]
Hi @victoriavhe previously sample used a beta version, can you update with our latest stable version 1.0.4?

**Comment by SogoGolf** [comment]
we just tried the sample and it crashed for us too. looks like you did not include the required GoogleService-Info.plist in the Runner project in Xcode (since you have dependencies on Firebase Messaging). you should add to the install instructions that the dev needs to create a Firebase project and download the plist etc..

```
could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.'
```

**Comment by adicatur** [comment]
Thanks for the feedback @SogoGolf, after add the GoogleService are you able to run the sample apps? or do you have any other issue?

**Comment by SogoGolf** [comment]
Yes it worked

**Comment by adicatur** [comment]
Awesome, thanks for the confirmation @SogoGolf, will create the docs and let you know too @victoriavhe

**Comment by victoriavhe** [comment]
ok great, thanks!

**Comment by apiep** [comment]
I will close this issue for now, feel free to reopen if the issue re-appear
